const LIFESTYLE_CATEGORIES = [
  "Accessories",
  "Active Life",
  "Adult Education",
  "Air",
  "Ammo",
  "Appliances",
  "Arcade",
  "Arts & Crafts",
  "Arts & Entertainment",
  "Auto",
  "Banks",
  "Bars",
  "Bath",
  "Battery",
  "Beaches",
  "Beauty & Spas",
  "Beer Bar",
  "Boating",
  "Boat",
  "Books",
  "Bowling",
  "Business",
  "Cafes",
  "Car",
  "Car Dealers",
  "Cards & Stationery",
  "Casinos",
  "Caterers",
  "Children",
  "Chiropractors",
  "Christmas Trees",
  "Cleaning",
  "Clothing",
  "Clubs",
  "Cocktail Bars",
  "Comedy",
  "Community Service/Non-Profit",
  "Computer",
  "Conditioning",
  "Cosmetics",
  "Cosmetics & Beauty Supply",
  "Country",
  "Country Clubs",
  "Crane",
  "Crafts",
  "Dive Bars",
  "Doctors",
  "Education",
  "Educational",
  "Electronics",
  "Entertainment",
  "Equipment",
  "Events",
  "Event Planning & Services",
  "Fashion",
  "Festivals",
  "Financial",
  "Fireworks",
  "Fishing",
  "Flowers",
  "Flowers & Gifts",
  "Food Stands",
  "Furniture",
  "Funeral",
  "Galleries",
  "Gas",
  "Gas Stations",
  "Gastropubs",
  "Gear",
  "Gifts",
  "Golf",
  "Gun",
  "Gun/Rifle Ranges",
  "Hair",
  "Hardware",
  "Health",
  "Health & Medical",
  "Health Markets",
  "Heating",
  "Herbal",
  "Home & Garden",
  "Hotels",
  "Hotels & Travel",
  "HVAC",
  "Indoor",
  "Irish Pub",
  "IT",
  "Jazz & Blues",
  "Kids Activities",
  "Karts",
  "Kitchen & Bath",
  "Kitchen Supplies",
  "Laser",
  "Leisure Centers",
  "Lessons",
  "Life",
  "Lounges",
  "Mental",
  "Massage",
  "Motor",
  "Motorcycles",
  "Movies (Cinema)",
  "Museum",
  "Music",
  "Music & Video",
  "Music Venues",
  "Nail",
  "Nail Salons",
  "Nightlife",
  "Outdoor",
  "Parks",
  "Performing Arts",
  "Playcenter",
  "Playgrounds",
  "Pool",
  "Pool Halls",
  "Professional Services",
  "Pub",
  "Pubs",
  "Race",
  "Rifle",
  "Repair",
  "Restaurants",
  "School",
  "Service",
  "Shopping",
  "Social Clubs",
  "Southern",
  "Spas",
  "Sports Bars",
  "Stationery",
  "Tag",
  "Tapas Bars",
  "Tennis",
  "Tex-Mex",
  "Tours",
  "Tracks",
  "Transportation",
  "Venues & Event Spaces",
  "Vehicles",
  "Wear",
  "Wine & Spirits",
  "Women's Clothing",
  "Yoga",
];

const FOOD_CATEGORIES = [
  "food",
  "bowls",
  "trucks",
  "restaurants",
  "bar",
  "bars",
  "cheesecakes",
  "american",
  "italian",
  "greek",
  "german",
  "austrian",
  "spanish",
  "argentinian",
  "mexican",
  "brazilian",
  "french",
  "english",
  "portuguese",
  "african",
  "japanese",
  "chinese",
  "korean",
  "chicken",
  "barbecue",
  "cakes",
  "cupcakes",
  "coffeshops",
  "coffee",
  "chocolatiers",
  "afghan",
  "armenian",
  "grocery",
  "hawaiian",
  "creperies",
  "bars",
  "beer",
  "colombian",
  "fruits",
  "veggies",
  "fast food",
  "kebab",
  "gelato",
  "ice cream",
  "tea",
  "pizza",
  "asian",
  "middle eastern",
  "cuban",
  "hot dogs",
  "sandwiches",
  "nightlife",
  "moroccan",
  "mongolian",
  "lounges",
  "latin american",
  "fish",
  "chips",
  "british",
  "donuts",
  "fondue",
  "wine",
  "russian",
  "olive",
  "syrian",
  "meat",
  "market",
  "lebanese",
  "dim sum",
  "crawl",
  "cajun",
  "creole",
  "gluten",
  "brew",
  "breakfast",
  "brunch",
  "buffets",
  "flavor",
  "falafel",
  "farmers",
  "dominican",
  "mediterran",
  "waffles",
  "noodles",
  "filipino",
  "beverage",
  "egyptian",
  "breweries",
  "desserts",
  "department",
  "blues",
  "jazz",
  "butcher",
  "brasseries",
  "bistros",
  "yogurt",
  "garden",
  "bagels",
  "irish",
  "iberian",
  "laotian",
  "juice",
  "pot",
  "herbs",
  "spices",
  "oriental",
  "wraps",
  "cooking",
  "delis",
  "dinners",
  "czech",
  "himalayan",
  "nepalese",
  "fusion",
  "caterers",
];

function formatCategory(category) {
  return category
    .split(" ")
    .map((word) =>
      word.length ? word[0].toUpperCase() + word.slice(1).toLowerCase() : ""
    )
    .join(" ");
}

const CATEGORY_OPTIONS = {
  food: Array.from(new Set(FOOD_CATEGORIES.map(formatCategory))),
  lifestyle: Array.from(new Set(LIFESTYLE_CATEGORIES.map(formatCategory))),
};

export { CATEGORY_OPTIONS, FOOD_CATEGORIES, LIFESTYLE_CATEGORIES };
