export const LIFESTYLE_KEYWORDS = [
  "life",
  "education",
  "entertainment",
  "parks",
  "appliances",
  "arcade",
  "crafts",
  "galleries",
  "auto",
  "battery",
  "business",
  "cinema",
  "clothing",
  "electronics",
  "motor",
  "vehicles",
  "school",
  "herbal",
  "comedy",
  "clubs",
  "gifts",
  "flowers",
  "equipment",
  "gas",
  "music",
  "museum",
  "laser",
  "tag",
  "golf",
  "lessons",
  "outdoor",
  "gear",
  "karts",
  "beaches",
  "accessories",
  "car",
  "dealers",
  "tours",
  "boating",
  "boat",
  "casinos",
  "classes",
  "cosmetics",
  "furniture",
  "fireworks",
  "fishing",
  "florists",
  "churches",
  "christmas trees",
  "crane",
  "clothing",
  "children",
  "spas",
  "heating",
  "air",
  "conditioning",
  "art",
  "galleries",
  "yoga",
  "DVD",
  "cleaning",
  "gun",
  "rifle",
  "ammo",
  "hair",
  "funeral",
  "furniture",
  "musicians",
  "motorcycles",
  "gear",
  "bath",
  "hotels",
  "health",
  "yelp events",
  "nail",
  "wear",
  "massage",
  "doctors",
  "repair",
  "pool",
  "pub",
  "race",
  "tracks",
  "fashion",
  "transportation",
  "financial",
  "educational",
  "books",
  "HVAC",
  "IT",
  "Computer",
  "hardware",
  "mental",
  "health",
  "counseling",
  "removal",
  "indoor",
  "playcenter",
  "care",
  "comedy",
  "country",
  "catonese",
  "car",
  "installation",
  "waxing",
  "drugstores",
  "banks",
];

export const FOOD_KEYWORDS = [
  "food",
  "bowls",
  "trucks",
  "restaurants",
  "cheesecakes",
  "american",
  "italian",
  "greek",
  "german",
  "austrian",
  "spanish",
  "argentinian",
  "mexican",
  "brazilian",
  "french",
  "english",
  "portuguese",
  "african",
  "japanese",
  "chinese",
  "korean",
  "chicken",
  "barbecue",
  "cakes",
  "cupcakes",
  "coffeshops",
  "coffe",
  "chocolatiers",
  "afghan",
  "armenian",
  "grocery",
  "hawaiian",
  "creperies",
  "bars",
  "beer",
  "colombian",
  "fruits",
  "veggies",
  "fast food",
  "kebab",
  "gelato",
  "ice cream",
  "tea",
  "pizza",
  "asian",
  "middle eastern",
  "cuban",
  "hot dogs",
  "sandwiches",
  "nightlife",
  "moroccan",
  "mongolian",
  "movers",
  "lounges",
  "Latin American",
  "fish",
  "chips",
  "british",
  "donuts",
  "fondue",
  "wine",
  "russian",
  "olive",
  "syrian",
  "meat",
  "market",
  "lebanese",
  "dim sum",
  "crawl",
  "cajun",
  "creole",
  "gluten",
  "brew",
  "breakfast",
  "brunch",
  "buffets",
  "flavor",
  "falafel",
  "farmers",
  "dominican",
  "mediterran",
  "waffles",
  "noodles",
  "filipino",
  "beverage",
  "egyptian",
  "breweries",
  "desserts",
  "department",
  "blues",
  "jazz",
  "butcher",
  "brasseries",
  "bistros",
  "batting",
  "cages",
  "yogurt",
  "garden",
  "home",
  "bagels",
  "irish",
  "iberian",
  "laotian",
  "juice",
  "pot",
  "herbs",
  "spices",
  "oriental",
  "wraps",
  "cooking",
  "delis",
  "dinners",
  "czech",
  "hymalaian",
  "nepalese",
  "fusion",
  "caterers",
];

function normalizeKeywords(keywords) {
  return keywords.map((keyword) => keyword.trim().toLowerCase()).filter(Boolean);
}

const NORMALIZED_LIFESTYLE = normalizeKeywords(LIFESTYLE_KEYWORDS);
const NORMALIZED_FOOD = normalizeKeywords(FOOD_KEYWORDS);

function matchesCategoryKeywords(categories = [], keywords = []) {
  return categories.some((category) => {
    const normalizedCategory = category.toLowerCase();
    return keywords.some((keyword) => normalizedCategory.includes(keyword));
  });
}

function inferTypeFromCategories(categories = []) {
  if (matchesCategoryKeywords(categories, NORMALIZED_LIFESTYLE)) return "lifestyle";
  if (matchesCategoryKeywords(categories, NORMALIZED_FOOD)) return "food";
  return null;
}

function restaurantMatchesType(restaurant, type = "food") {
  const inferredType = inferTypeFromCategories(restaurant.categories);
  const effectiveType = restaurant.type ?? inferredType;

  if (type === "lifestyle") return effectiveType === "lifestyle";
  if (type === "food") return effectiveType !== "lifestyle";
  return true;
}

export {
  matchesCategoryKeywords,
  inferTypeFromCategories,
  restaurantMatchesType,
};
